In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,MinMaxScaler,PowerTransformer
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn import set_config
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score,mean_absolute_error
from sklearn.ensemble import RandomForestRegressor

import optuna
import dagshub
import mlflow

c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# load data

df = pd.read_csv(r'C:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\notebooks\data_eda.csv')
df.sample(2)

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
13017,INDORES06DEL02,37.0,4.5,22.728163,75.884212,22.748163,75.904212,2022-03-26,cloudy,high,...,INDO,26,3,saturday,1,15.0,11.0,morning,3.025321,short
16045,RANCHIRES13DEL02,39.0,4.7,23.374989,85.335486,23.424989,85.385486,2022-03-13,cloudy,low,...,RANCHI,13,3,sunday,1,10.0,23.0,night,7.546265,medium

In [5]:
set_config(transform_output='pandas')

In [6]:
df.isnull().sum()

rider_id                   0
age                     1854
ratings                 1908
restaurant_latitude     3630
restaurant_longitude    3630
delivery_latitude       3630
delivery_longitude      3630
order_date                 0
weather                  525
traffic                  510
vehicle_condition          0
type_of_order              0
type_of_vehicle            0
multiple_deliveries      993
festival                 228
city_type               1198
time_taken                 0
city_name                  0
order_day                  0
order_month                0
order_day_of_week          0
is_weekend                 0
pickup_time_minutes     1640
order_time_hour         1640
order_time_of_day       2070
distance                3630
distance_type           3630
dtype: int64

In [7]:
# dropping columns
df.drop(columns=['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"],
                    inplace=True)

df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
44132,37.0,4.8,windy,low,2,meal,scooter,0.0,no,urban,18,0,5.0,night,20.206901,very_long
24592,35.0,4.8,sandstorms,low,2,drinks,scooter,0.0,no,metropolitian,27,1,10.0,morning,1.554499,short

## Model Building

In [8]:
temp_df = df.copy().dropna()
temp_df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
35750,29.0,4.6,windy,medium,2,drinks,motorcycle,1.0,no,urban,18,0,15.0,evening,10.711186,long
19953,26.0,4.9,sunny,low,2,buffet,scooter,0.0,no,metropolitian,21,0,5.0,night,4.544232,short

In [9]:
temp_df.isnull().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [10]:
X = temp_df.drop(columns=['time_taken'])
y = temp_df['time_taken']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape,y_test.shape

((30156, 15), (7539,))

In [11]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [22]:
# Transforming target column

pt = PowerTransformer(method='yeo-johnson')

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

y_train_pt

             x0
0      2.028672
1      0.554539
2     -2.024267
3     -0.173699
4      0.554539
...         ...
30151  0.457580
30152 -0.173699
30153 -1.350937
30154  0.047111
30155  0.257130

[30156 rows x 1 columns]

In [13]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [14]:
# build a preprocessor

preprocessor = ColumnTransformer(
    transformers=
    [
        ("scale", MinMaxScaler(), num_cols),
        ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False), nominal_cat_cols),
        ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],handle_unknown="use_encoded_value",unknown_value=-1), ordinal_cat_cols)
    ],
        remainder="passthrough",n_jobs=-1,verbose_feature_names_out=False
)

preprocessor

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [15]:
# build the pipeline

processing_pipeline = Pipeline(steps=[
                                ("preprocess",preprocessor)
                            ])

processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [16]:
X_train_trans = processing_pipeline.fit_transform(X_train)
X_test_trans = processing_pipeline.transform(X_test)

## Optuna HP tuning

In [17]:
dagshub.init(repo_owner='jay-kanakia', repo_name='swiggy_delivery_time_prediction', mlflow=True)
mlflow.set_tracking_uri('https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow')
mlflow.set_experiment(experiment_name='Exp 4 : RF Optuna HF tuning')

Accessing as jay-kanakia

Initialized MLflow to track repo "jay-kanakia/swiggy_delivery_time_prediction"

Repository jay-kanakia/swiggy_delivery_time_prediction initialized!

<Experiment: artifact_location='mlflow-artifacts:/f78ff6a2bd624df5b3400b1f635740f5', creation_time=1775393931096, experiment_id='5', last_update_time=1775393931096, lifecycle_stage='active', name='Exp 4 : RF Optuna HF tuning', tags={}, workspace='default'>

In [23]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            'n_estimators' : trial.suggest_int('n_estimators',10,500),
            'max_depth' : trial.suggest_int('max_depth',1,30),
            'max_features' : trial.suggest_categorical('max_features',[None,'sqrt','log2']),
            'min_samples_split' : trial.suggest_int('min_samples_split',2,10),
            'min_samples_leaf' : trial.suggest_int('min_samples_leaf',1,10),
            'max_samples' : trial.suggest_float('max_samples',0.5,1),
            'random_state' : 42,
            'n_jobs' : -1
        }

        # log model parameters
        mlflow.log_params(params)

        # build the model
        rfg = RandomForestRegressor(**params)
        rfg.fit(X_train_trans,y_train)

        # perform cross validation
        model = TransformedTargetRegressor(regressor=rfg,transformer=pt)

        # perform cross validation
        score  = cross_val_score(model,X_train_trans,y_train,cv=5,scoring='neg_mean_absolute_error',n_jobs=-1)

        # mean score
        mean_score  = -score.mean()

        # get the prediction
        y_pred_train = rfg.predict(X_train_trans)
        y_pred_test = rfg.predict(X_test_trans)

        # logging metrics
        mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train))
        mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test))
        mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train))
        mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test))
        mlflow.log_metric("cross_val",mean_score)

        return mean_score

In [24]:
# create optuna study
study = optuna.create_study(direction="minimize",study_name='Optuna Light GBM HP')

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=50,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # build the model on best parameters
    best_rf = RandomForestRegressor(**study.best_params)
    best_rf.fit(X_train_trans,y_train)

    # get the predictions
    y_pred_train = best_rf.predict(X_train_trans)
    y_pred_test = best_rf.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    #train the model
    model = TransformedTargetRegressor(regressor=best_rf,transformer=pt)
    
    # perform cross validation
    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_rf,artifact_path="model")

[I 2026-04-05 21:26:57,543] A new study created in memory with name: Optuna Light GBM HP
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run worried-wasp-314 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/3eec3ea33bcb42ce939ca80a81c5e7b8
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run ambitious-crane-519 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/57d16d3f3b004d56979f6c36b38999f1
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:   2%|▏         | 1/50 [01:02<50:59, 62.44s/it]

[I 2026-04-05 21:28:01,324] Trial 4 finished with value: 3.0915787506101453 and parameters: {'n_estimators': 233, 'max_depth': 25, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_samples': 0.5192638383577522}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run resilient-shrimp-723 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d38b95d6908c40e68eabd38057e9f658
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:   4%|▍         | 2/50 [01:07<22:58, 28.72s/it]

[I 2026-04-05 21:28:06,714] Trial 1 finished with value: 3.267082446097393 and parameters: {'n_estimators': 29, 'max_depth': 19, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_samples': 0.657931261717986}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run skittish-asp-923 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/5de1bb4561804641b8590624d93228f4
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run big-wolf-604 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/2fdd272338d24ccfa04401f136d94aac
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:   6%|▌         | 3/50 [01:15<14:58, 19.12s/it]

[I 2026-04-05 21:28:14,578] Trial 15 finished with value: 6.080048452348192 and parameters: {'n_estimators': 179, 'max_depth': 2, 'max_features': 'log2', 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_samples': 0.6740724236922018}. Best is trial 4 with value: 3.0915787506101453.

Best trial: 4. Best value: 3.09158:   8%|▊         | 4/50 [01:18<09:52, 12.88s/it]

[I 2026-04-05 21:28:17,697] Trial 3 finished with value: 3.103807789099077 and parameters: {'n_estimators': 45, 'max_depth': 26, 'max_features': None, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_samples': 0.5820758340063584}. Best is trial 4 with value: 3.0915787506101453.

Best trial: 4. Best value: 3.09158:  10%|█         | 5/50 [01:20<06:44,  9.00s/it]

[I 2026-04-05 21:28:19,796] Trial 11 finished with value: 3.3583330432865557 and parameters: {'n_estimators': 77, 'max_depth': 13, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_samples': 0.6831689979874418}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run useful-elk-946 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d5097b0f8d7c47c581b5142e3965bf17
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run bright-crow-603 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/c4645c913a6441128ef8406fdf1accaf
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

[I 2026-04-05 21:28:41,864] Trial 7 finished with value: 3.4507738164400363 and parameters: {'n_estimators': 101, 'max_depth': 9, 'max_features': None, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_samples': 0.9384257334319003}. Best is trial 4 with value: 3.0915787506101453.

Best trial: 4. Best value: 3.09158:  12%|█▏        | 6/50 [01:45<10:39, 14.54s/it]

🏃 View run gifted-cod-895 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/444c763cb445450cb032b7f6ec5adec9
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:  12%|█▏        | 6/50 [01:46<10:39, 14.54s/it]

[I 2026-04-05 21:28:45,879] Trial 5 finished with value: 3.093642677009202 and parameters: {'n_estimators': 75, 'max_depth': 24, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_samples': 0.585995495621443}. Best is trial 4 with value: 3.0915787506101453.

Best trial: 4. Best value: 3.09158:  16%|█▌        | 8/50 [01:47<04:50,  6.93s/it]

[I 2026-04-05 21:28:45,895] Trial 0 finished with value: 5.968803946752549 and parameters: {'n_estimators': 157, 'max_depth': 2, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_samples': 0.8287657927340245}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run bemused-mule-427 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/3e60fe85d06b4cd0bafe66b09f8def11
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:  18%|█▊        | 9/50 [02:33<13:16, 19.43s/it]

[I 2026-04-05 21:29:32,992] Trial 12 finished with value: 3.231870836017299 and parameters: {'n_estimators': 203, 'max_depth': 23, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_samples': 0.8061646216934568}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run beautiful-bug-608 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f85476fc69ff4222b759d0d08ffd4dac
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run popular-auk-813 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f773134bf635443eb96f4e5135418532
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:  20%|██        | 10/50 [03:06<15:41, 23.54s/it]

[I 2026-04-05 21:30:06,026] Trial 8 finished with value: 3.3037788846733633 and parameters: {'n_estimators': 262, 'max_depth': 26, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_samples': 0.9093699649319317}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run intrigued-moth-917 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d3e7ba1e387043f186912018be05e1c5
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run indecisive-bird-702 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/4bf8f8938d604142a10a28369a239776
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run likeable-panda-550 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/3e73494fe33641cba328a42b89be9aff
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 4. Best value: 3.09158:  22%|██▏       | 11/50 [03:45<18:22, 28.27s/it]

[I 2026-04-05 21:30:45,058] Trial 10 finished with value: 3.248450022910754 and parameters: {'n_estimators': 418, 'max_depth': 28, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_samples': 0.8106191570303359}. Best is trial 4 with value: 3.0915787506101453.
🏃 View run abrasive-penguin-821 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d39dfb6eb48f4568ab360bab0947ca8d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run amazing-hawk-514 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/5c76d1431c9b4486a97b90ea67aaaa0e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run fun-yak-959 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/6f1bee14d5c64e8b9449db82dc74914d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run legendary-crane-638 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d8275461fb384a4d968e488611c9a759
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run wistful-newt-12 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/8d1b081143a846bb9b7e0473aac6222e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 2. Best value: 3.09048:  24%|██▍       | 12/50 [03:56<14:36, 23.07s/it]

[I 2026-04-05 21:30:56,221] Trial 2 finished with value: 3.090480327921455 and parameters: {'n_estimators': 441, 'max_depth': 20, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_samples': 0.9779778426809854}. Best is trial 2 with value: 3.090480327921455.

Best trial: 2. Best value: 3.09048:  26%|██▌       | 13/50 [03:57<10:03, 16.32s/it]

[I 2026-04-05 21:30:57,011] Trial 17 finished with value: 3.5894422609233425 and parameters: {'n_estimators': 235, 'max_depth': 11, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_samples': 0.7161171619911855}. Best is trial 2 with value: 3.090480327921455.

Best trial: 6. Best value: 3.09012:  28%|██▊       | 14/50 [03:58<07:01, 11.71s/it]

[I 2026-04-05 21:30:58,077] Trial 6 finished with value: 3.090122226267794 and parameters: {'n_estimators': 371, 'max_depth': 27, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_samples': 0.7068033161602383}. Best is trial 6 with value: 3.090122226267794.

Best trial: 6. Best value: 3.09012:  30%|███       | 15/50 [04:00<05:05,  8.74s/it]

[I 2026-04-05 21:30:59,928] Trial 18 finished with value: 3.332190939272686 and parameters: {'n_estimators': 23, 'max_depth': 16, 'max_features': 'log2', 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_samples': 0.763287944702966}. Best is trial 6 with value: 3.090122226267794.

Best trial: 6. Best value: 3.09012:  32%|███▏      | 16/50 [04:01<03:38,  6.43s/it]

[I 2026-04-05 21:31:00,979] Trial 19 finished with value: 4.513316433371451 and parameters: {'n_estimators': 402, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_samples': 0.7041907586567522}. Best is trial 6 with value: 3.090122226267794.

Best trial: 6. Best value: 3.09012:  34%|███▍      | 17/50 [04:03<02:48,  5.12s/it]

[I 2026-04-05 21:31:03,050] Trial 20 finished with value: 3.676748742155463 and parameters: {'n_estimators': 233, 'max_depth': 10, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_samples': 0.8354464420819305}. Best is trial 6 with value: 3.090122226267794.

Best trial: 6. Best value: 3.09012:  36%|███▌      | 18/50 [04:07<02:35,  4.86s/it]

[I 2026-04-05 21:31:07,293] Trial 16 finished with value: 3.2918351626171045 and parameters: {'n_estimators': 270, 'max_depth': 18, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_samples': 0.7248067690355358}. Best is trial 6 with value: 3.090122226267794.
🏃 View run wistful-grub-334 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/b5e6feecbba44557b5f72c8e7b01f36b
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run unleashed-wolf-558 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/d12a39c4146e4a608d4d903bf5894581
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  38%|███▊      | 19/50 [04:18<03:20,  6.48s/it]

[I 2026-04-05 21:31:17,441] Trial 9 finished with value: 3.0890525143981358 and parameters: {'n_estimators': 205, 'max_depth': 24, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_samples': 0.872171434301396}. Best is trial 9 with value: 3.0890525143981358.
🏃 View run bright-mink-41 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/8a30593f7d0440e3b60fe63364035d43
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run abrasive-hawk-3 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/1cab808bda6f475db77f4803b2090f99
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  40%|████      | 20/50 [04:28<03:44,  7.50s/it]

[I 2026-04-05 21:31:27,137] Trial 22 finished with value: 3.3482212618136957 and parameters: {'n_estimators': 381, 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_samples': 0.9863684864455051}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 9. Best value: 3.08905:  40%|████      | 20/50 [04:30<03:44,  7.50s/it]

[I 2026-04-05 21:31:29,130] Trial 24 finished with value: 3.258131716072872 and parameters: {'n_estimators': 282, 'max_depth': 23, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_samples': 0.8887961785150017}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 9. Best value: 3.08905:  42%|████▏     | 21/50 [04:31<03:04,  6.38s/it]

🏃 View run vaunted-crane-601 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/5b0c1a30fdc94d34b0165f75eb4ed7a9
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

[I 2026-04-05 21:31:34,146] Trial 14 finished with value: 3.9529115614157684 and parameters: {'n_estimators': 460, 'max_depth': 8, 'max_features': 'log2', 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_samples': 0.5072130867998277}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 9. Best value: 3.08905:  42%|████▏     | 21/50 [04:35<03:04,  6.38s/it]

Best trial: 9. Best value: 3.08905:  44%|████▍     | 22/50 [04:38<02:46,  5.95s/it]

[I 2026-04-05 21:31:36,691] Trial 23 finished with value: 3.0920851889528214 and parameters: {'n_estimators': 111, 'max_depth': 22, 'max_features': None, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_samples': 0.6831935159725062}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 9. Best value: 3.08905:  48%|████▊     | 24/50 [05:21<06:53, 15.91s/it]

[I 2026-04-05 21:32:20,367] Trial 13 finished with value: 4.240841380792551 and parameters: {'n_estimators': 21, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_samples': 0.7072339100515213}. Best is trial 9 with value: 3.0890525143981358.
🏃 View run charming-sow-247 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/dab6a1591d5e400f93416ec8e38ce10d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  50%|█████     | 25/50 [07:48<23:00, 55.23s/it]

[I 2026-04-05 21:34:45,403] Trial 25 finished with value: 3.0893494128386916 and parameters: {'n_estimators': 389, 'max_depth': 30, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_samples': 0.5626739619613882}. Best is trial 9 with value: 3.0890525143981358.
🏃 View run sassy-perch-803 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/2f2e0135a3e248f0b0966094cfb68c79
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  50%|█████     | 25/50 [09:57<23:00, 55.23s/it]

[I 2026-04-05 21:36:56,512] Trial 21 finished with value: 3.372145026462789 and parameters: {'n_estimators': 386, 'max_depth': 17, 'max_features': 'log2', 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_samples': 0.5730934541297186}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 9. Best value: 3.08905:  52%|█████▏    | 26/50 [10:08<32:12, 80.50s/it]

🏃 View run bouncy-finch-912 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/bf33e116bfc54a809397123bf0797005
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  54%|█████▍    | 27/50 [11:29<31:01, 80.95s/it]

[I 2026-04-05 21:38:28,684] Trial 26 finished with value: 3.0907761824592535 and parameters: {'n_estimators': 350, 'max_depth': 21, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_samples': 0.5005868498306798}. Best is trial 9 with value: 3.0890525143981358.
🏃 View run burly-shoat-240 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/05b5c0dad94744628d4f818d1074c321
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run valuable-sponge-863 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/97e049acb40f445484c12ee7a51d79bc
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 9. Best value: 3.08905:  56%|█████▌    | 28/50 [12:47<29:19, 79.98s/it]

[I 2026-04-05 21:39:46,503] Trial 31 finished with value: 3.0911303067162885 and parameters: {'n_estimators': 496, 'max_depth': 20, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_samples': 0.9981188350216242}. Best is trial 9 with value: 3.0890525143981358.

Best trial: 33. Best value: 3.08776:  58%|█████▊    | 29/50 [12:49<19:48, 56.62s/it]

[I 2026-04-05 21:39:48,656] Trial 33 finished with value: 3.087763356347309 and parameters: {'n_estimators': 345, 'max_depth': 30, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_samples': 0.8898320903498909}. Best is trial 33 with value: 3.087763356347309.
🏃 View run selective-lark-216 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/86b3c544f22f43f88d410fff6a4a82cf
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run beautiful-stork-137 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/2571ecebe80b4718957786771ef39204
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  60%|██████    | 30/50 [13:00<14:18, 42.92s/it]

[I 2026-04-05 21:39:59,649] Trial 30 finished with value: 3.0893539845635756 and parameters: {'n_estimators': 479, 'max_depth': 30, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_samples': 0.8921931804273912}. Best is trial 33 with value: 3.087763356347309.
🏃 View run learned-toad-319 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/b2275519c37f47f1b8da5f0d52b5dd4f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run merciful-quail-669 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/ffcf567f117841c8902eaaabb9baa284
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  62%|██████▏   | 31/50 [13:05<09:59, 31.57s/it]

[I 2026-04-05 21:40:04,749] Trial 27 finished with value: 3.090731483402741 and parameters: {'n_estimators': 499, 'max_depth': 20, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_samples': 0.9890467203872955}. Best is trial 33 with value: 3.087763356347309.
🏃 View run resilient-gull-957 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f989ee7dd2944650adaf5b6c62f7448c
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run rare-mole-562 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/a9d343ecb32c41d5b54543e590f5bbf2
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  64%|██████▍   | 32/50 [13:11<07:11, 23.95s/it]

[I 2026-04-05 21:40:10,912] Trial 38 finished with value: 3.091615680882261 and parameters: {'n_estimators': 314, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9968326156358343}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  66%|██████▌   | 33/50 [13:17<05:16, 18.64s/it]

[I 2026-04-05 21:40:17,148] Trial 28 finished with value: 3.0912109049348024 and parameters: {'n_estimators': 500, 'max_depth': 22, 'max_features': None, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_samples': 0.9923726766362692}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  68%|██████▊   | 34/50 [13:18<03:32, 13.27s/it]

[I 2026-04-05 21:40:17,898] Trial 29 finished with value: 3.092141552612794 and parameters: {'n_estimators': 332, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9998059058609694}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  70%|███████   | 35/50 [13:21<02:34, 10.29s/it]

[I 2026-04-05 21:40:21,115] Trial 32 finished with value: 3.088968425972987 and parameters: {'n_estimators': 492, 'max_depth': 21, 'max_features': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_samples': 0.8961722708139646}. Best is trial 33 with value: 3.087763356347309.
🏃 View run caring-roo-208 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f35597ff206a4104a698379bf09b5996
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run traveling-boar-701 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/1e80ac7e0cdd41ec9d65b26cb02e0b5f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run sassy-mink-37 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/6c83a7ecfef447a88f6c7b3cc6d8c731
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  70%|███████   | 35/50 [13:43<02:34, 10.29s/it]

🏃 View run clean-loon-872 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f4c7160849174603bc424fe3ddbe4a2c
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
[I 2026-04-05 21:40:42,289] Trial 34 finished with value: 3.090915771512618 and parameters: {'n_estimators': 498, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9904832693857217}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  72%|███████▏  | 36/50 [13:55<03:13, 13.84s/it]

[I 2026-04-05 21:40:54,268] Trial 35 finished with value: 3.092327935223243 and parameters: {'n_estimators': 328, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9995672654918968}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  74%|███████▍  | 37/50 [13:59<02:54, 13.44s/it]

[I 2026-04-05 21:40:57,582] Trial 39 finished with value: 3.0921592130685527 and parameters: {'n_estimators': 332, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9886291884238374}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  76%|███████▌  | 38/50 [14:38<02:05, 10.44s/it]

[I 2026-04-05 21:41:33,503] Trial 40 finished with value: 3.093425439731236 and parameters: {'n_estimators': 330, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_samples': 0.6319906437318767}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  78%|███████▊  | 39/50 [14:44<03:46, 20.59s/it]

🏃 View run burly-fawn-388 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/994076079e2f45079173ef41ab19cd40
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  78%|███████▊  | 39/50 [15:14<03:46, 20.59s/it]

[I 2026-04-05 21:42:12,864] Trial 45 finished with value: 3.0881890329339834 and parameters: {'n_estimators': 343, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_samples': 0.8752035687844699}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  80%|████████  | 40/50 [15:15<03:57, 23.78s/it]

🏃 View run bouncy-finch-442 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/106d413f93134353b30def2b3d00697a
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  80%|████████  | 40/50 [15:43<03:57, 23.78s/it]

[I 2026-04-05 21:42:41,858] Trial 46 finished with value: 3.088950401061756 and parameters: {'n_estimators': 329, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_samples': 0.8637036386118927}. Best is trial 33 with value: 3.087763356347309.

Best trial: 33. Best value: 3.08776:  82%|████████▏ | 41/50 [15:43<03:45, 25.05s/it]

🏃 View run capable-sponge-697 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/f6db372f9d6f49a89ee5569e2427f344
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  84%|████████▍ | 42/50 [16:01<03:04, 23.01s/it]

[I 2026-04-05 21:42:59,741] Trial 43 finished with value: 3.087923593759033 and parameters: {'n_estimators': 310, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_samples': 0.8604794237989976}. Best is trial 33 with value: 3.087763356347309.
🏃 View run persistent-mink-44 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/6d8d34d93839487ba4f247c0c4a20bc8
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🏃 View run rogue-boar-302 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/ace5404b77c54e1f872853a5094a27fd
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 33. Best value: 3.08776:  88%|████████▊ | 44/50 [16:25<01:38, 16.34s/it]

[I 2026-04-05 21:43:24,960] Trial 37 finished with value: 3.0902779630454917 and parameters: {'n_estimators': 320, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9381084671029849}. Best is trial 33 with value: 3.087763356347309.
[I 2026-04-05 21:43:25,103] Trial 44 finished with value: 3.0889638806540693 and parameters: {'n_estimators': 329, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_samples': 0.8637529091295573}. Best is trial 33 with value: 3.087763356347309.
🏃 View run bouncy-hare-59 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/a70bc8e0ad214d0d9fac8238ca83ff40
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 47. Best value: 3.08733:  90%|█████████ | 45/50 [16:32<01:07, 13.45s/it]

[I 2026-04-05 21:43:31,575] Trial 47 finished with value: 3.0873333050729133 and parameters: {'n_estimators': 433, 'max_depth': 28, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_samples': 0.851873041953807}. Best is trial 47 with value: 3.0873333050729133.
🏃 View run magnificent-swan-478 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/be819da6de6b4c658fcb96212dc39ad6
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 47. Best value: 3.08733:  92%|█████████▏| 46/50 [16:41<00:48, 12.02s/it]

[I 2026-04-05 21:43:40,510] Trial 48 finished with value: 3.087561111542709 and parameters: {'n_estimators': 438, 'max_depth': 28, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_samples': 0.8612621399332873}. Best is trial 47 with value: 3.0873333050729133.
🏃 View run bald-colt-258 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/666b74d7ec71495bb99dcdab58baf24f
🏃 View run dazzling-fowl-229 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/7a1d46a824354bf6907bc6b9a152fb56
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 47. Best value: 3.08733:  96%|█████████▌| 48/50 [16:42<00:12,  6.25s/it]

[I 2026-04-05 21:43:42,030] Trial 42 finished with value: 3.0895307110378694 and parameters: {'n_estimators': 322, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_samples': 0.7637236018404504}. Best is trial 47 with value: 3.0873333050729133.
[I 2026-04-05 21:43:42,107] Trial 36 finished with value: 3.0926760783272145 and parameters: {'n_estimators': 338, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_samples': 0.9934992806312655}. Best is trial 47 with value: 3.0873333050729133.
🏃 View run treasured-finch-411 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/abfbdf47e8214dc68d7f458f3aec3411
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 47. Best value: 3.08733:  98%|█████████▊| 49/50 [16:44<00:04,  4.89s/it]

[I 2026-04-05 21:43:43,888] Trial 41 finished with value: 3.093266410170489 and parameters: {'n_estimators': 311, 'max_depth': 30, 'max_features': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_samples': 0.6119665263472024}. Best is trial 47 with value: 3.0873333050729133.
🏃 View run serious-loon-306 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/e04ebeb8a72c49bdaf311bbc75e944d2
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

Best trial: 49. Best value: 3.08694: 100%|██████████| 50/50 [16:52<00:00, 20.26s/it]

[I 2026-04-05 21:43:52,249] Trial 49 finished with value: 3.0869398198716285 and parameters: {'n_estimators': 424, 'max_depth': 28, 'max_features': None, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_samples': 0.8542421813553751}. Best is trial 49 with value: 3.0869398198716285.

2026/04/05 21:45:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/05 21:45:50 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5/runs/b00cb95ef4224d738e69e52f46e37b51
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/5

In [25]:
study.best_params

{'n_estimators': 424,
 'max_depth': 28,
 'max_features': None,
 'min_samples_split': 8,
 'min_samples_leaf': 6,
 'max_samples': 0.8542421813553751}

In [26]:
study.best_value

3.0869398198716285

In [27]:
optuna.visualization.plot_optimization_history(study)

In [29]:
optuna.visualization.plot_param_importances(study)

In [30]:
optuna.visualization.plot_slice(study)