In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,MinMaxScaler,PowerTransformer
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn import set_config
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score,mean_absolute_error

import optuna
import dagshub
import mlflow

c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# load data

df = pd.read_csv(r'C:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\notebooks\data_eda.csv')
df.sample(2)

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
18794,INDORES08DEL01,37.0,4.7,22.725748,75.898497,22.765747,75.938497,2022-04-03,fog,high,...,INDO,3,4,sunday,1,5.0,15.0,afternoon,6.050406,medium
9311,KNPRES16DEL01,25.0,4.7,26.482581,80.315628,26.492581,80.325628,2022-02-11,stormy,low,...,KNP,11,2,friday,0,5.0,10.0,morning,1.492284,short

In [3]:
set_config(transform_output='pandas')

In [4]:
df.isnull().sum()

rider_id                   0
age                     1854
ratings                 1908
restaurant_latitude     3630
restaurant_longitude    3630
delivery_latitude       3630
delivery_longitude      3630
order_date                 0
weather                  525
traffic                  510
vehicle_condition          0
type_of_order              0
type_of_vehicle            0
multiple_deliveries      993
festival                 228
city_type               1198
time_taken                 0
city_name                  0
order_day                  0
order_month                0
order_day_of_week          0
is_weekend                 0
pickup_time_minutes     1640
order_time_hour         1640
order_time_of_day       2070
distance                3630
distance_type           3630
dtype: int64

In [5]:
# dropping columns
df.drop(columns=['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"],
                    inplace=True)

df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
30271,33.0,4.7,sunny,low,2,meal,scooter,1.0,no,urban,29,0,15.0,night,19.761066,very_long
1939,32.0,4.4,sandstorms,jam,1,meal,scooter,0.0,no,metropolitian,33,0,15.0,evening,4.657620,short

# Model Building

In [6]:
temp_df = df.copy().dropna()

In [7]:
temp_df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
16269,23.0,4.7,stormy,high,1,buffet,motorcycle,0.0,no,urban,20,1,5.0,morning,1.489846,short
41088,26.0,5.0,fog,medium,2,buffet,electric_scooter,1.0,no,urban,32,1,10.0,evening,10.906471,long

In [8]:
temp_df.isnull().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [9]:
X = temp_df.drop(columns=['time_taken'])
y = temp_df['time_taken']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape,y_test.shape

((30156, 15), (7539,))

In [10]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [11]:
# Transforming target column

pt = PowerTransformer(method='yeo-johnson')

y_train_trans = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_trans = pt.transform(y_test.values.reshape(-1,1))

y_train_trans

             x0
0      2.028672
1      0.554539
2     -2.024267
3     -0.173699
4      0.554539
...         ...
30151  0.457580
30152 -0.173699
30153 -1.350937
30154  0.047111
30155  0.257130

[30156 rows x 1 columns]

In [12]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [13]:
# build a preprocessor

preprocessor = ColumnTransformer(
    transformers=
    [
        ("scale", MinMaxScaler(), num_cols),
        ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False), nominal_cat_cols),
        ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],handle_unknown="use_encoded_value",unknown_value=-1), ordinal_cat_cols)
    ],
        remainder="passthrough",n_jobs=-1,verbose_feature_names_out=False
)

preprocessor

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [14]:
# build the pipeline

processing_pipeline = Pipeline(steps=[
                                ("preprocess",preprocessor)
                            ])

processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [15]:
X_train_trans = processing_pipeline.fit_transform(X_train)
X_test_trans = processing_pipeline.transform(X_test)

## Optuna

In [16]:
dagshub.init(repo_owner='jay-kanakia', repo_name='swiggy_delivery_time_prediction', mlflow=True)
mlflow.set_tracking_uri('https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow')
mlflow.set_experiment(experiment_name='Exp 3 : Optuna LightGBM HP')

Accessing as jay-kanakia

Initialized MLflow to track repo "jay-kanakia/swiggy_delivery_time_prediction"

Repository jay-kanakia/swiggy_delivery_time_prediction initialized!

<Experiment: artifact_location='mlflow-artifacts:/cafda3023e6e469abe8b2a835bb63d03', creation_time=1775392161345, experiment_id='4', last_update_time=1775392161345, lifecycle_stage='active', name='Exp 3 : Optuna LightGBM HP', tags={}, workspace='default'>

In [17]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            'n_estimator' : trial.suggest_int('n_estimator',10,200),
            'max_depth' : trial.suggest_int('max_depth',1,40),
            'learning_rate' :  trial.suggest_float('learning_rate',0.01,0.3),
            'subsample' :  trial.suggest_float('subsample',0.5,1),
            "num_leaves": trial.suggest_int("num_leaves", 20, 150),
            'min_sum_hessian_in_leaf' :  trial.suggest_int('min_child_weight',5,20),
            'min_split_gain' : trial.suggest_float('min_split_gain',0,10),
            'reg_lambda' : trial.suggest_float('reg_lambda',0,100),
            'random_state' : 42,
            'n_jobs' : -1
        }

        # log model parameters
        mlflow.log_params(params)

        lgbm = LGBMRegressor(**params)

        model = TransformedTargetRegressor(regressor=lgbm,transformer=pt)

        model.fit(X_train_trans,y_train)

        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)

        mlflow.log_metric('Traning accuracy',r2_score(y_train,y_pred_train))
        mlflow.log_metric('Testing accuracy',r2_score(y_test,y_pred_test))

        score = cross_val_score(model,X_train_trans,y_train,cv=5,scoring='neg_mean_absolute_error',n_jobs=-1)

        mean_score = -(score.mean())

        mlflow.log_metric('cross_val_error',mean_score)

        return mean_score

In [19]:
# create study object

study = optuna.create_study(direction='minimize',study_name='LGBM HP')

with mlflow.start_run(run_name='Best Model'):
    
    # optimize the objective function
    study.optimize(objective,n_trials=50,n_jobs=-1,show_progress_bar=True)

    # log best parameters
    mlflow.log_params(study.best_params)

    # train the model on best parameters
    best_lgbm = LGBMRegressor(**study.best_params)

    model = TransformedTargetRegressor(regressor=best_lgbm,transformer=pt)

    model.fit(X_train_trans,y_train)

    # get the prediction
    y_pred_train = model.predict(X_train_trans)
    y_pred_test = model.predict(X_test_trans)

    scores = cross_val_score(model,X_train_trans,y_train,scoring='neg_mean_absolute_error',cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_lgbm,artifact_path='model')

[I 2026-04-05 18:23:01,769] A new study created in memory with name: LGBM HP
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run merciful-jay-632 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/cfbc4384521947f792911bba54377ac8
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run wise-grub-774 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/a63e09c3c9724ee5aa9b695eca27f8c2
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run chill-snipe-806 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/bd4cadb47f6341f8b3403aa61a65203d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run incongruous-crow-585 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/162d31d99ee4443fbfc52149bbe4720a
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run masked-bee-296 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/ded5fb6c801845c188dc4dda7a865b5d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run unruly-newt-671 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/2146d1ce790a4073a59bf83a300a1125
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 7. Best value: 3.69024:   2%|▏         | 1/50 [01:01<50:29, 61.82s/it]

[I 2026-04-05 18:24:05,493] Trial 7 finished with value: 3.690242655790324 and parameters: {'n_estimator': 191, 'max_depth': 6, 'learning_rate': 0.26687280091297094, 'subsample': 0.8372687850315467, 'num_leaves': 57, 'min_child_weight': 9, 'min_split_gain': 7.898421704106909, 'reg_lambda': 20.354639819327236}. Best is trial 7 with value: 3.690242655790324.
🏃 View run sincere-slug-269 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/0f72aa14149240ce9915022b764da07b
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 2. Best value: 3.5328:   4%|▍         | 2/50 [01:03<21:17, 26.61s/it]

[I 2026-04-05 18:24:07,477] Trial 2 finished with value: 3.5327954084678965 and parameters: {'n_estimator': 137, 'max_depth': 14, 'learning_rate': 0.202491115286428, 'subsample': 0.5622369082698842, 'num_leaves': 65, 'min_child_weight': 9, 'min_split_gain': 1.6142617608915766, 'reg_lambda': 25.652927003788317}. Best is trial 2 with value: 3.5327954084678965.

Best trial: 2. Best value: 3.5328:   6%|▌         | 3/50 [01:05<12:04, 15.41s/it]

[I 2026-04-05 18:24:09,541] Trial 10 finished with value: 3.570701599807952 and parameters: {'n_estimator': 161, 'max_depth': 33, 'learning_rate': 0.14317630382011373, 'subsample': 0.5964452609718272, 'num_leaves': 23, 'min_child_weight': 16, 'min_split_gain': 2.615377450755293, 'reg_lambda': 87.43964449815638}. Best is trial 2 with value: 3.5327954084678965.

Best trial: 2. Best value: 3.5328:   8%|▊         | 4/50 [01:08<08:02, 10.49s/it]

[I 2026-04-05 18:24:12,494] Trial 15 finished with value: 3.7138269834104007 and parameters: {'n_estimator': 103, 'max_depth': 24, 'learning_rate': 0.2746530846720344, 'subsample': 0.6177005535291297, 'num_leaves': 35, 'min_child_weight': 16, 'min_split_gain': 5.139414821669082, 'reg_lambda': 65.24596059739}. Best is trial 2 with value: 3.5327954084678965.

Best trial: 2. Best value: 3.5328:  10%|█         | 5/50 [01:09<05:16,  7.04s/it]

[I 2026-04-05 18:24:13,424] Trial 5 finished with value: 3.9172308180055877 and parameters: {'n_estimator': 112, 'max_depth': 5, 'learning_rate': 0.02226194233627877, 'subsample': 0.7386324767003085, 'num_leaves': 62, 'min_child_weight': 15, 'min_split_gain': 9.68284139726764, 'reg_lambda': 19.45376950332436}. Best is trial 2 with value: 3.5327954084678965.

Best trial: 1. Best value: 3.46898:  12%|█▏        | 6/50 [01:10<03:39,  5.00s/it]

[I 2026-04-05 18:24:14,457] Trial 1 finished with value: 3.468977826963493 and parameters: {'n_estimator': 189, 'max_depth': 38, 'learning_rate': 0.13631451384586424, 'subsample': 0.5334960198254186, 'num_leaves': 21, 'min_child_weight': 18, 'min_split_gain': 1.3797850115736499, 'reg_lambda': 56.91212844560782}. Best is trial 1 with value: 3.468977826963493.
🏃 View run tasteful-moth-83 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/a0e3ed4ac3744c5195740dceb1e501ef
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run salty-zebra-182 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/02fdceeb8a6d45a19b7f0ca75127f479
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 1. Best value: 3.46898:  14%|█▍        | 7/50 [01:22<05:14,  7.31s/it]

[I 2026-04-05 18:24:26,531] Trial 11 finished with value: 3.4900834263226606 and parameters: {'n_estimator': 58, 'max_depth': 31, 'learning_rate': 0.11104439854384093, 'subsample': 0.532929599145104, 'num_leaves': 23, 'min_child_weight': 15, 'min_split_gain': 1.3683633873443812, 'reg_lambda': 83.43021443361025}. Best is trial 1 with value: 3.468977826963493.
🏃 View run big-owl-965 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/760899482e644ba5bdb8128433302cf5
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 1. Best value: 3.46898:  16%|█▌        | 8/50 [01:26<04:24,  6.30s/it]

[I 2026-04-05 18:24:30,646] Trial 4 finished with value: 3.76049004641985 and parameters: {'n_estimator': 146, 'max_depth': 40, 'learning_rate': 0.11527564092689892, 'subsample': 0.918120908497067, 'num_leaves': 58, 'min_child_weight': 9, 'min_split_gain': 9.34282131155789, 'reg_lambda': 29.825416283961825}. Best is trial 1 with value: 3.468977826963493.
🏃 View run debonair-skunk-417 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/133a8d9e57094837ade67bd0edac1889
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run monumental-slug-146 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/61ecec3343ea4cb8b93dd3221280eb6e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 1. Best value: 3.46898:  18%|█▊        | 9/50 [01:47<07:23, 10.83s/it]

[I 2026-04-05 18:24:51,424] Trial 6 finished with value: 3.6633013738774443 and parameters: {'n_estimator': 74, 'max_depth': 24, 'learning_rate': 0.21759659951697707, 'subsample': 0.6277587699273686, 'num_leaves': 96, 'min_child_weight': 20, 'min_split_gain': 4.920814707981853, 'reg_lambda': 57.33206755567021}. Best is trial 1 with value: 3.468977826963493.
🏃 View run likeable-robin-458 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/d043e34ad8da43c9865ffacbe198f176
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 1. Best value: 3.46898:  20%|██        | 10/50 [01:59<07:26, 11.17s/it]

[I 2026-04-05 18:25:03,389] Trial 12 finished with value: 5.6988951382953354 and parameters: {'n_estimator': 189, 'max_depth': 1, 'learning_rate': 0.025894946976334626, 'subsample': 0.5276327637029726, 'num_leaves': 43, 'min_child_weight': 11, 'min_split_gain': 0.6333884222036557, 'reg_lambda': 1.0079152363565602}. Best is trial 1 with value: 3.468977826963493.
🏃 View run serious-mare-528 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/29beac89b927420fbaace253a3f15e5e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 1. Best value: 3.46898:  22%|██▏       | 11/50 [02:05<06:15,  9.64s/it]

[I 2026-04-05 18:25:09,544] Trial 9 finished with value: 3.4946760331481217 and parameters: {'n_estimator': 96, 'max_depth': 7, 'learning_rate': 0.16268044386163988, 'subsample': 0.8164685021023473, 'num_leaves': 84, 'min_child_weight': 16, 'min_split_gain': 1.6221968415103105, 'reg_lambda': 75.63715204897456}. Best is trial 1 with value: 3.468977826963493.
🏃 View run fortunate-skink-109 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/9d9e75b8c63546dc9684916d85cb35b4
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  24%|██▍       | 12/50 [02:09<05:00,  7.90s/it]

[I 2026-04-05 18:25:13,460] Trial 8 finished with value: 3.2654010232850097 and parameters: {'n_estimator': 110, 'max_depth': 16, 'learning_rate': 0.054144885903996624, 'subsample': 0.5885229216351464, 'num_leaves': 133, 'min_child_weight': 20, 'min_split_gain': 0.27918607075017143, 'reg_lambda': 18.740245272329147}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run bright-trout-34 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/578ddb8e21074b2eaaed9a09a08d348d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run popular-ox-887 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/c9b50810057349ddb340d31138e46e30
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  26%|██▌       | 13/50 [02:13<04:08,  6.73s/it]

[I 2026-04-05 18:25:17,487] Trial 17 finished with value: 3.764270698495298 and parameters: {'n_estimator': 51, 'max_depth': 13, 'learning_rate': 0.17861333933641196, 'subsample': 0.9630692866561831, 'num_leaves': 111, 'min_child_weight': 17, 'min_split_gain': 9.850231964277398, 'reg_lambda': 29.8320416480926}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  28%|██▊       | 14/50 [02:21<04:17,  7.15s/it]

[I 2026-04-05 18:25:25,625] Trial 18 finished with value: 3.4273521509995293 and parameters: {'n_estimator': 172, 'max_depth': 28, 'learning_rate': 0.2137149780780153, 'subsample': 0.6525412634020312, 'num_leaves': 41, 'min_child_weight': 18, 'min_split_gain': 0.9181426992019648, 'reg_lambda': 99.2169028325313}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  30%|███       | 15/50 [02:22<03:03,  5.26s/it]

[I 2026-04-05 18:25:26,487] Trial 21 finished with value: 3.631960206528395 and parameters: {'n_estimator': 90, 'max_depth': 36, 'learning_rate': 0.19157587425680048, 'subsample': 0.7384758358422163, 'num_leaves': 35, 'min_child_weight': 5, 'min_split_gain': 4.246940897323438, 'reg_lambda': 94.35220596284599}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run omniscient-sheep-109 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/128dc880fe5147fcb6773456c0897a9d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run unleashed-deer-289 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/a39daa4bc1934ba085bbef85b2202f05
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run likeable-skink-390 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/111576f87b934737b15e650ca4dbfc23
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  32%|███▏      | 16/50 [02:36<04:29,  7.92s/it]

[I 2026-04-05 18:25:40,598] Trial 20 finished with value: 3.720449857546993 and parameters: {'n_estimator': 54, 'max_depth': 18, 'learning_rate': 0.10375137110767624, 'subsample': 0.9000037063434473, 'num_leaves': 69, 'min_child_weight': 9, 'min_split_gain': 5.589074080258419, 'reg_lambda': 21.768594908891615}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  34%|███▍      | 17/50 [02:39<03:32,  6.45s/it]

[I 2026-04-05 18:25:43,638] Trial 22 finished with value: 3.545421186605831 and parameters: {'n_estimator': 127, 'max_depth': 30, 'learning_rate': 0.09980417361783718, 'subsample': 0.5780470867494847, 'num_leaves': 127, 'min_child_weight': 5, 'min_split_gain': 1.600659745656492, 'reg_lambda': 99.7053110234423}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  36%|███▌      | 18/50 [02:40<02:26,  4.59s/it]

[I 2026-04-05 18:25:43,887] Trial 3 finished with value: 3.7669894075837553 and parameters: {'n_estimator': 61, 'max_depth': 28, 'learning_rate': 0.05506367112982407, 'subsample': 0.5479091186118714, 'num_leaves': 87, 'min_child_weight': 20, 'min_split_gain': 8.562226995951235, 'reg_lambda': 33.17367610594878}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run clean-dog-144 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/b2e81d4291e04a7b81586917ce90f60e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  38%|███▊      | 19/50 [02:48<02:52,  5.57s/it]

[I 2026-04-05 18:25:51,732] Trial 23 finished with value: 3.721739887880058 and parameters: {'n_estimator': 98, 'max_depth': 20, 'learning_rate': 0.2748833952070054, 'subsample': 0.7545730306012743, 'num_leaves': 127, 'min_child_weight': 20, 'min_split_gain': 6.407533359086015, 'reg_lambda': 96.39310167410692}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  40%|████      | 20/50 [02:48<02:02,  4.08s/it]

[I 2026-04-05 18:25:52,339] Trial 16 finished with value: 3.751098288146443 and parameters: {'n_estimator': 84, 'max_depth': 38, 'learning_rate': 0.040904525041609685, 'subsample': 0.9430214604008271, 'num_leaves': 66, 'min_child_weight': 7, 'min_split_gain': 6.789756576328905, 'reg_lambda': 95.70387739037885}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run peaceful-donkey-816 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/89caf444e7134d2382af48f590c8380e
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  42%|████▏     | 21/50 [03:03<03:35,  7.44s/it]

[I 2026-04-05 18:26:07,599] Trial 24 finished with value: 3.729538256699919 and parameters: {'n_estimator': 112, 'max_depth': 12, 'learning_rate': 0.25803201216168686, 'subsample': 0.9805189586537386, 'num_leaves': 132, 'min_child_weight': 11, 'min_split_gain': 7.701411849313052, 'reg_lambda': 20.37559520747082}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run marvelous-shrike-792 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/0f3bc4cf85c94d9e8d39cf5c29e9e478
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run resilient-stoat-527 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/6d166f59084c43d492b530c6db476474
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  44%|████▍     | 22/50 [03:14<03:56,  8.46s/it]

[I 2026-04-05 18:26:18,437] Trial 25 finished with value: 3.654772477491804 and parameters: {'n_estimator': 17, 'max_depth': 33, 'learning_rate': 0.0893900569013451, 'subsample': 0.6919994325544224, 'num_leaves': 117, 'min_child_weight': 18, 'min_split_gain': 4.199359540568171, 'reg_lambda': 93.05345884531627}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run overjoyed-gnu-996 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/83c800365d79425787d929a1b8089a7a
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  46%|████▌     | 23/50 [03:22<03:45,  8.36s/it]

[I 2026-04-05 18:26:26,556] Trial 19 finished with value: 3.525228840362055 and parameters: {'n_estimator': 174, 'max_depth': 17, 'learning_rate': 0.23837280720629883, 'subsample': 0.7035938175182098, 'num_leaves': 103, 'min_child_weight': 8, 'min_split_gain': 2.503776153365923, 'reg_lambda': 80.67149455638632}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  48%|████▊     | 24/50 [03:26<03:02,  7.03s/it]

[I 2026-04-05 18:26:30,487] Trial 26 finished with value: 3.6666505996103673 and parameters: {'n_estimator': 21, 'max_depth': 19, 'learning_rate': 0.07389950652758502, 'subsample': 0.6902257779760932, 'num_leaves': 150, 'min_child_weight': 20, 'min_split_gain': 3.6306795040358892, 'reg_lambda': 39.30012564843928}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run gifted-koi-366 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/1b8403b57a434a879ad8ba9207581f40
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run rumbling-dolphin-553 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/8f9f293d33c34194b3822284233838ea
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  50%|█████     | 25/50 [03:40<03:47,  9.11s/it]

[I 2026-04-05 18:26:44,464] Trial 28 finished with value: 3.643319403792708 and parameters: {'n_estimator': 17, 'max_depth': 17, 'learning_rate': 0.057663028980881534, 'subsample': 0.661005623717466, 'num_leaves': 147, 'min_child_weight': 20, 'min_split_gain': 3.2680421920573273, 'reg_lambda': 44.078990540985814}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run loud-wasp-368 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/f0717abf5b5443b1a3362cae811755e6
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run defiant-ray-580 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/69cbb9288cc2441baa29709b7eee22f9
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run auspicious-midge-67 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/2a4eed4ff5e74f6383faa8ad0f26d8f9
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 8. Best value: 3.2654:  52%|█████▏    | 26/50 [03:50<03:45,  9.38s/it]

[I 2026-04-05 18:26:54,485] Trial 27 finished with value: 3.6600323642019426 and parameters: {'n_estimator': 22, 'max_depth': 18, 'learning_rate': 0.07299771924813386, 'subsample': 0.6926829215217674, 'num_leaves': 127, 'min_child_weight': 20, 'min_split_gain': 3.54970487617475, 'reg_lambda': 46.98228818741398}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  54%|█████▍    | 27/50 [03:51<02:38,  6.88s/it]

[I 2026-04-05 18:26:55,527] Trial 13 finished with value: 4.378027421616548 and parameters: {'n_estimator': 61, 'max_depth': 1, 'learning_rate': 0.1543952705438195, 'subsample': 0.9158602056998609, 'num_leaves': 80, 'min_child_weight': 12, 'min_split_gain': 6.763133305257904, 'reg_lambda': 8.21486181277532}. Best is trial 8 with value: 3.2654010232850097.

Best trial: 8. Best value: 3.2654:  56%|█████▌    | 28/50 [03:53<01:58,  5.40s/it]

[I 2026-04-05 18:26:57,473] Trial 29 finished with value: 3.6542738903880703 and parameters: {'n_estimator': 31, 'max_depth': 18, 'learning_rate': 0.07258453427672444, 'subsample': 0.6901162222008878, 'num_leaves': 140, 'min_child_weight': 20, 'min_split_gain': 3.3155087361073203, 'reg_lambda': 40.21414585262646}. Best is trial 8 with value: 3.2654010232850097.
🏃 View run aged-kite-523 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/b20adc1b081748f8b7dbbd6248b89648
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run smiling-calf-28 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/df78c0efbb1d41059564ad6704724255
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 31. Best value: 3.13359:  58%|█████▊    | 29/50 [03:57<01:44,  4.99s/it]

[I 2026-04-05 18:27:01,503] Trial 31 finished with value: 3.1335855059676945 and parameters: {'n_estimator': 14, 'max_depth': 14, 'learning_rate': 0.23819591956320227, 'subsample': 0.6762903892048757, 'num_leaves': 147, 'min_child_weight': 13, 'min_split_gain': 0.036199141504626775, 'reg_lambda': 44.199864141364046}. Best is trial 31 with value: 3.1335855059676945.
🏃 View run upbeat-lamb-696 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/29792063ee4b44baac8af64e45b0c078
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 31. Best value: 3.13359:  60%|██████    | 30/50 [04:06<02:03,  6.17s/it]

[I 2026-04-05 18:27:10,438] Trial 33 finished with value: 3.660466105608946 and parameters: {'n_estimator': 165, 'max_depth': 14, 'learning_rate': 0.24150413414489635, 'subsample': 0.6694851313923679, 'num_leaves': 150, 'min_child_weight': 13, 'min_split_gain': 3.4413435820771037, 'reg_lambda': 41.68440853675823}. Best is trial 31 with value: 3.1335855059676945.

Best trial: 31. Best value: 3.13359:  62%|██████▏   | 31/50 [04:09<01:39,  5.25s/it]

[I 2026-04-05 18:27:13,540] Trial 35 finished with value: 3.178916193405629 and parameters: {'n_estimator': 34, 'max_depth': 15, 'learning_rate': 0.23216138114842308, 'subsample': 0.6642074631989023, 'num_leaves': 148, 'min_child_weight': 13, 'min_split_gain': 0.1117540890065852, 'reg_lambda': 43.61980879362409}. Best is trial 31 with value: 3.1335855059676945.

Best trial: 34. Best value: 3.11365:  64%|██████▍   | 32/50 [04:12<01:22,  4.56s/it]

[I 2026-04-05 18:27:16,496] Trial 34 finished with value: 3.113649973447473 and parameters: {'n_estimator': 20, 'max_depth': 13, 'learning_rate': 0.22939179670776155, 'subsample': 0.6712285694155066, 'num_leaves': 144, 'min_child_weight': 13, 'min_split_gain': 0.0034217361394887624, 'reg_lambda': 42.858111022840106}. Best is trial 34 with value: 3.113649973447473.

Best trial: 34. Best value: 3.11365:  66%|██████▌   | 33/50 [04:23<01:50,  6.50s/it]

[I 2026-04-05 18:27:27,501] Trial 32 finished with value: 3.6227577905763595 and parameters: {'n_estimator': 22, 'max_depth': 25, 'learning_rate': 0.2313022598749311, 'subsample': 0.6767107927273475, 'num_leaves': 140, 'min_child_weight': 13, 'min_split_gain': 3.1605426795865164, 'reg_lambda': 42.6416622074816}. Best is trial 34 with value: 3.113649973447473.
🏃 View run rebellious-perch-108 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/5631d90e3b6f4dbca60a84b24e2e9847
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run peaceful-gnu-632 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/a33841dd52394ea196163a4cfd40f697
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run receptive-frog-708 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/fe0529ddceb64d2a94cb14b5e7ad9fd6
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 34. Best value: 3.11365:  68%|██████▊   | 34/50 [04:38<02:24,  9.04s/it]

[I 2026-04-05 18:27:42,494] Trial 37 finished with value: 3.155014260897849 and parameters: {'n_estimator': 171, 'max_depth': 26, 'learning_rate': 0.14878305884613674, 'subsample': 0.5003928490303733, 'num_leaves': 141, 'min_child_weight': 18, 'min_split_gain': 0.0808485036251681, 'reg_lambda': 43.913327910045716}. Best is trial 34 with value: 3.113649973447473.

Best trial: 34. Best value: 3.11365:  70%|███████   | 35/50 [04:40<01:43,  6.92s/it]

[I 2026-04-05 18:27:44,466] Trial 30 finished with value: 3.6151049123744166 and parameters: {'n_estimator': 131, 'max_depth': 18, 'learning_rate': 0.07354855634370734, 'subsample': 0.6576615959176821, 'num_leaves': 140, 'min_child_weight': 19, 'min_split_gain': 3.1203334285788085, 'reg_lambda': 46.412387091223856}. Best is trial 34 with value: 3.113649973447473.

Best trial: 34. Best value: 3.11365:  72%|███████▏  | 36/50 [04:52<01:58,  8.44s/it]

[I 2026-04-05 18:27:56,436] Trial 40 finished with value: 3.2235719206786184 and parameters: {'n_estimator': 167, 'max_depth': 26, 'learning_rate': 0.14258314243202447, 'subsample': 0.5095010059701466, 'num_leaves': 46, 'min_child_weight': 18, 'min_split_gain': 0.19836765447658156, 'reg_lambda': 68.81778119672396}. Best is trial 34 with value: 3.113649973447473.
🏃 View run colorful-flea-172 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/c03b68bd44974bb8b3182cd8be6e06fc
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run shivering-fawn-274 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/676817ff58b74b02a7ae1576933f1d50
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run mysterious-goat-910 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/f46b4db0f81043a2b4893a003a76f608
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run zealous-smelt-50 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/9c6bfe49db494996b8615c7677c2125b
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run serious-eel-981 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/be5b86843eed4bc7933e0e5ed33b4456
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 34. Best value: 3.11365:  74%|███████▍  | 37/50 [05:07<02:15, 10.42s/it]

[I 2026-04-05 18:28:11,478] Trial 38 finished with value: 3.1650651454331333 and parameters: {'n_estimator': 200, 'max_depth': 25, 'learning_rate': 0.2993894014244016, 'subsample': 0.5053805037062897, 'num_leaves': 48, 'min_child_weight': 18, 'min_split_gain': 0.04837809479559829, 'reg_lambda': 46.711032249953746}. Best is trial 34 with value: 3.113649973447473.

Best trial: 44. Best value: 3.1092:  76%|███████▌  | 38/50 [05:09<01:34,  7.92s/it]

[I 2026-04-05 18:28:13,556] Trial 44 finished with value: 3.109202935814433 and parameters: {'n_estimator': 200, 'max_depth': 25, 'learning_rate': 0.22115542857546375, 'subsample': 0.6351188850278723, 'num_leaves': 116, 'min_child_weight': 18, 'min_split_gain': 0.012008093473736992, 'reg_lambda': 56.14207085908463}. Best is trial 44 with value: 3.109202935814433.
🏃 View run chill-cat-440 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/f3b4c930bafd48bb9c58d336919d17e5
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  78%|███████▊  | 39/50 [05:13<01:13,  6.72s/it]

[I 2026-04-05 18:28:17,465] Trial 0 finished with value: 3.702122710270861 and parameters: {'n_estimator': 156, 'max_depth': 21, 'learning_rate': 0.28869457478339466, 'subsample': 0.8789946470604402, 'num_leaves': 97, 'min_child_weight': 5, 'min_split_gain': 5.10658409196835, 'reg_lambda': 79.35408504294308}. Best is trial 44 with value: 3.109202935814433.
🏃 View run sassy-kit-906 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/eb48064c6bd941c68282a9b973883455
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run shivering-fowl-410 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/86aa39d475b14560aa18f11820e18228
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  80%|████████  | 40/50 [05:16<00:56,  5.62s/it]

[I 2026-04-05 18:28:20,531] Trial 14 finished with value: 3.6302043041372962 and parameters: {'n_estimator': 174, 'max_depth': 27, 'learning_rate': 0.21210053920170535, 'subsample': 0.9177920939165669, 'num_leaves': 127, 'min_child_weight': 11, 'min_split_gain': 4.102224008757812, 'reg_lambda': 29.475804420133265}. Best is trial 44 with value: 3.109202935814433.

Best trial: 44. Best value: 3.1092:  82%|████████▏ | 41/50 [05:19<00:43,  4.81s/it]

[I 2026-04-05 18:28:23,443] Trial 39 finished with value: 3.2733777545282243 and parameters: {'n_estimator': 200, 'max_depth': 24, 'learning_rate': 0.14279969634724754, 'subsample': 0.5029922380889642, 'num_leaves': 149, 'min_child_weight': 18, 'min_split_gain': 0.24542784605467816, 'reg_lambda': 46.84581649049869}. Best is trial 44 with value: 3.109202935814433.
🏃 View run spiffy-conch-793 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/cf78cc5bf264452db2de6b228252e2f6
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  84%|████████▍ | 42/50 [05:21<00:31,  3.99s/it]

[I 2026-04-05 18:28:25,534] Trial 43 finished with value: 3.163417088533793 and parameters: {'n_estimator': 172, 'max_depth': 23, 'learning_rate': 0.2304719613506931, 'subsample': 0.6394158414187167, 'num_leaves': 138, 'min_child_weight': 18, 'min_split_gain': 0.0714701156212661, 'reg_lambda': 57.318264391120245}. Best is trial 44 with value: 3.109202935814433.
🏃 View run caring-squid-349 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/1c1717ed1f8149c197a695fbf319606d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  86%|████████▌ | 43/50 [05:24<00:25,  3.69s/it]

[I 2026-04-05 18:28:28,503] Trial 46 finished with value: 3.202713616568123 and parameters: {'n_estimator': 39, 'max_depth': 10, 'learning_rate': 0.2995412751639167, 'subsample': 0.623370065108567, 'num_leaves': 139, 'min_child_weight': 13, 'min_split_gain': 0.11686327043266644, 'reg_lambda': 54.5441395662732}. Best is trial 44 with value: 3.109202935814433.

Best trial: 44. Best value: 3.1092:  88%|████████▊ | 44/50 [05:25<00:17,  2.87s/it]

[I 2026-04-05 18:28:29,453] Trial 47 finished with value: 3.2279162294529042 and parameters: {'n_estimator': 35, 'max_depth': 10, 'learning_rate': 0.18348937819963165, 'subsample': 0.6241529132768683, 'num_leaves': 137, 'min_child_weight': 14, 'min_split_gain': 0.17276201456938275, 'reg_lambda': 52.604796491493744}. Best is trial 44 with value: 3.109202935814433.
🏃 View run respected-stoat-535 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/2cfc726381f74eeaa6d01a1ffbd534af
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  90%|█████████ | 45/50 [05:28<00:14,  2.95s/it]

[I 2026-04-05 18:28:32,601] Trial 36 finished with value: 3.2250257892477285 and parameters: {'n_estimator': 170, 'max_depth': 26, 'learning_rate': 0.23525514368968453, 'subsample': 0.6742702487332778, 'num_leaves': 146, 'min_child_weight': 18, 'min_split_gain': 0.14572422985828482, 'reg_lambda': 44.382665019308746}. Best is trial 44 with value: 3.109202935814433.

Best trial: 44. Best value: 3.1092:  92%|█████████▏| 46/50 [05:30<00:10,  2.65s/it]

[I 2026-04-05 18:28:34,557] Trial 42 finished with value: 3.1224893143112515 and parameters: {'n_estimator': 173, 'max_depth': 23, 'learning_rate': 0.23971461517834097, 'subsample': 0.5025049581079225, 'num_leaves': 140, 'min_child_weight': 18, 'min_split_gain': 0.003612949013371891, 'reg_lambda': 55.013702532913676}. Best is trial 44 with value: 3.109202935814433.

Best trial: 44. Best value: 3.1092:  94%|█████████▍| 47/50 [05:32<00:07,  2.44s/it]

[I 2026-04-05 18:28:36,490] Trial 41 finished with value: 3.1952143220105302 and parameters: {'n_estimator': 172, 'max_depth': 23, 'learning_rate': 0.29606441751065593, 'subsample': 0.6466705680291427, 'num_leaves': 138, 'min_child_weight': 18, 'min_split_gain': 0.09430397593076356, 'reg_lambda': 55.720852638974094}. Best is trial 44 with value: 3.109202935814433.
🏃 View run adaptable-robin-653 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/e65ea7908dfa48e8a33e2f8bc4097578
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4
🏃 View run intelligent-mule-342 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/e534a375d6af44c7aa205aa53e3a4774
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 44. Best value: 3.1092:  96%|█████████▌| 48/50 [05:36<00:05,  2.91s/it]

[I 2026-04-05 18:28:40,491] Trial 49 finished with value: 3.1466876580375485 and parameters: {'n_estimator': 38, 'max_depth': 10, 'learning_rate': 0.29326734223101136, 'subsample': 0.7735492929302684, 'num_leaves': 140, 'min_child_weight': 14, 'min_split_gain': 0.04978837997780381, 'reg_lambda': 55.135918618094735}. Best is trial 44 with value: 3.109202935814433.
🏃 View run sincere-wolf-397 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/de9354c413ca4d0092b76bdbc527e05b
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

Best trial: 48. Best value: 3.0986:  98%|█████████▊| 49/50 [05:38<00:02,  2.63s/it]

[I 2026-04-05 18:28:42,471] Trial 48 finished with value: 3.098601299582346 and parameters: {'n_estimator': 40, 'max_depth': 11, 'learning_rate': 0.18024722308848545, 'subsample': 0.7972018508352986, 'num_leaves': 118, 'min_child_weight': 14, 'min_split_gain': 0.007311476316166993, 'reg_lambda': 54.73782637648871}. Best is trial 48 with value: 3.098601299582346.

Best trial: 48. Best value: 3.0986: 100%|██████████| 50/50 [05:39<00:00,  6.80s/it]

[I 2026-04-05 18:28:43,505] Trial 45 finished with value: 3.3334875341490653 and parameters: {'n_estimator': 40, 'max_depth': 10, 'learning_rate': 0.293314854531882, 'subsample': 0.5051324377019635, 'num_leaves': 139, 'min_child_weight': 13, 'min_split_gain': 0.2748051376025549, 'reg_lambda': 54.79728324305178}. Best is trial 48 with value: 3.098601299582346.

c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but PowerTransformer was fitted without feature names
  warnings.warn(

[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002642 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator

2026/04/05 18:28:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/05 18:29:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run Best Model at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4/runs/3db03d2ee71d41c4af16b5f7cf395c47
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/4

In [21]:
study.best_params

{'n_estimator': 40,
 'max_depth': 11,
 'learning_rate': 0.18024722308848545,
 'subsample': 0.7972018508352986,
 'num_leaves': 118,
 'min_child_weight': 14,
 'min_split_gain': 0.007311476316166993,
 'reg_lambda': 54.73782637648871}

In [22]:
study.best_value

3.098601299582346

In [23]:
optuna.visualization.plot_optimization_history(study)

In [25]:
optuna.visualization.plot_param_importances(study)

In [26]:
optuna.visualization.plot_slice(study)