In [43]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import r2_score,mean_absolute_error

In [2]:
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
import optuna
import dagshub
import mlflow

c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from sklearn import set_config
set_config(transform_output='pandas')

In [4]:
# Load the data
df = pd.read_csv(r'C:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\notebooks\data_eda.csv')
df.sample(2)

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
29964,JAPRES06DEL02,36.0,4.2,26.911927,75.797282,26.961927,75.847282,2022-03-13,fog,jam,...,JAP,13,3,sunday,1,5.0,20.0,evening,7.448364,medium
42622,COIMBRES04DEL01,20.0,4.8,11.024839,77.007003,11.064839,77.047003,2022-03-15,windy,medium,...,COIMB,15,3,tuesday,0,15.0,15.0,afternoon,6.232153,medium

In [5]:
# dropping unnecessary columns

df.drop(columns=['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"],inplace=True)

In [6]:
df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
19377,38.0,4.1,sandstorms,medium,0,drinks,motorcycle,2.0,no,metropolitian,40,0,10.0,afternoon,10.587733,long
33127,26.0,4.8,sandstorms,low,2,snack,motorcycle,0.0,no,metropolitian,16,0,5.0,night,4.656991,short

In [7]:
df.isnull().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
is_weekend                0
pickup_time_minutes    1640
order_time_of_day      2070
distance               3630
distance_type          3630
dtype: int64

In [8]:
missing_col = df.isnull().any(axis=0).loc[lambda x : x].index
missing_col

Index(['age', 'ratings', 'weather', 'traffic', 'multiple_deliveries',
       'festival', 'city_type', 'pickup_time_minutes', 'order_time_of_day',
       'distance', 'distance_type'],
      dtype='object')

# Dropping missing values

In [9]:
temp_df = df.copy().dropna()
temp_df.sample(2)

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
23024,39.0,4.9,sandstorms,jam,2,buffet,motorcycle,1.0,no,metropolitian,26,0,5.0,night,9.192333,medium
25154,36.0,4.6,cloudy,jam,0,meal,motorcycle,0.0,no,metropolitian,34,0,15.0,evening,7.761839,medium

In [10]:
temp_df.shape

(37695, 16)

In [11]:
temp_df.isnull().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [12]:
X = temp_df.drop(columns = ['time_taken'])
y = temp_df['time_taken']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape,y_test.shape

((30156, 15), (7539,))

In [13]:
# target column transform

pt = PowerTransformer(method='yeo-johnson')

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

y_train_pt

             x0
0      2.028672
1      0.554539
2     -2.024267
3     -0.173699
4      0.554539
...         ...
30151  0.457580
30152 -0.173699
30153 -1.350937
30154  0.047111
30155  0.257130

[30156 rows x 1 columns]

## Preprocessing

In [14]:
# do basic preprocessing

num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather','type_of_order',
                    'type_of_vehicle',"festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [15]:
for col in ordinal_cat_cols:
    print(f'col name {col} : {temp_df[col].unique()}')

col name traffic : ['high' 'jam' 'low' 'medium']
col name distance_type : ['short' 'very_long' 'medium' 'long']

In [16]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [17]:
preprocessor = ColumnTransformer(
    [
        ('scaling',MinMaxScaler(),num_cols),
        ('OneHotEncoder',OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore'),nominal_cat_cols),
        ('OrdinalEncoding',OrdinalEncoder(categories=[traffic_order,distance_type_order],handle_unknown='use_encoded_value',unknown_value=-1),ordinal_cat_cols)
    ],
    remainder='passthrough',verbose_feature_names_out=False,n_jobs=-1
)

preprocessor

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('scaling', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('OneHotEncoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('OrdinalEncoding',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [18]:
# build model Pipeline

pipeline = Pipeline(
    [
        ('preprocessor',preprocessor)
    ]
)

pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('scaling', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('OrdinalEncoding',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [19]:
X_train_trans = pipeline.fit_transform(X_train)
X_test_trans = pipeline.transform(X_test)

X_train_trans.sample(2)

,age,ratings,pickup_time_minutes,distance,weather_fog,weather_sandstorms,weather_stormy,weather_sunny,weather_windy,type_of_order_drinks,...,city_type_semi-urban,city_type_urban,is_weekend_1,order_time_of_day_evening,order_time_of_day_morning,order_time_of_day_night,traffic,distance_type,vehicle_condition,multiple_deliveries
24593,0.526316,0.96,0.5,0.561656,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,2,1.0
44792,0.894737,0.80,0.0,0.243669,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2,0.0

## Optuna HyperParameter tuning

In [20]:
dagshub.init(repo_owner='jay-kanakia', repo_name='swiggy_delivery_time_prediction', mlflow=True)
mlflow.set_tracking_uri('https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow')
mlflow.set_experiment(experiment_name='Exp 2 : Model Selection with Optuna HP')

Accessing as jay-kanakia

Initialized MLflow to track repo "jay-kanakia/swiggy_delivery_time_prediction"

Repository jay-kanakia/swiggy_delivery_time_prediction initialized!

<Experiment: artifact_location='mlflow-artifacts:/ba2bb6f5d73b429eb2b858c065e71ecc', creation_time=1775374351700, experiment_id='3', last_update_time=1775374351700, lifecycle_stage='active', name='Exp 2 : Model Selection with Optuna HP', tags={'mlflow.experimentKind': 'custom_model_development'}, workspace='default'>

In [21]:
def objective(trial):

    with mlflow.start_run(nested=True):

        model_name = trial.suggest_categorical('model',['RF','GB','XGB','LGBM'])

        if model_name == 'SVM':
            kernel_svm = trial.suggest_categorical('kernel_svm',['linear','poly','rbf'])
            
            if kernel_svm == 'linear':
                c_linear = trial.suggest_float('c_linear',0.001,100,log=True)
                model = SVR(kernel = 'linear',C = c_linear)

            elif kernel_svm == 'poly':
                c_poly = trial.suggest_float('c_poly',0,10)
                degree_poly = trial.suggest_int('degree_poly',1,5)
                model = SVR(kernel='poly',degree=degree_poly,C = c_poly)

            else:
                c_rbf = trial.suggest_float('c_rbf',0,10)
                gamma_rbf = trial.suggest_float('gamma_rbf',0.0001,10,log=True)
                model = SVR(kernel = 'rbf',C = c_rbf,gamma = gamma_rbf)

        elif model_name == 'RF':
            n_estimator_rf = trial.suggest_int('n_estimator_rf',10,200)
            max_depth_rf = trial.suggest_int('max_depth_rf',2,20)
            model = RandomForestRegressor(n_estimators=n_estimator_rf,max_depth=max_depth_rf,random_state=42,n_jobs=-1)

        elif model_name == 'GB':
            n_estimator_gb = trial.suggest_int('n_estimator_gb',10,200)
            learning_rate_gb  = trial.suggest_float('learning_rate_gb',0.01,0.3)
            max_depth_gb = trial.suggest_int('max_depth_gb',2,20)
            model = GradientBoostingRegressor(n_estimators=n_estimator_gb,learning_rate=learning_rate_gb,max_depth=max_depth_gb,random_state=42)

        elif model_name == 'XGB':
            n_estimator_xgb = trial.suggest_int('n_estimator_xgb',10,200)
            learning_rate_xgb  = trial.suggest_float('learning_rate_xgb',0.01,0.3)
            max_depth_xgb = trial.suggest_int('max_depth_xgb',2,20)
            model = XGBRegressor(n_estimators=n_estimator_xgb,learning_rate=learning_rate_xgb,max_depth=max_depth_xgb,random_state=42)

        elif model_name == 'LGBM':
            n_estimator_lgbm = trial.suggest_int('n_estimator_lgbm',10,200)
            learning_rate_lgbm = trial.suggest_float('learning_rate_lgbm', 0.01, 0.1)
            max_depth_lgbm = trial.suggest_int('max_depth_lgbm',2,20)
            num_leaves = trial.suggest_int('num_leaves', 20, 150)
            min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 10, 50)
            model = LGBMRegressor(n_estimators=n_estimator_lgbm,learning_rate=learning_rate_lgbm,max_depth=max_depth_lgbm,random_state=42,n_jobs=-1)

        elif model_name == 'KNN':
            n_neighbors_knn = trial.suggest_int('n_neighbors_knn',1,25)
            weight_knn = trial.suggest_categorical('weight_knn',['uniform','distance'])
            model = KNeighborsRegressor(n_neighbors=n_neighbors_knn,weights=weight_knn)


        # train model
        model.fit(X_train_trans,y_train_pt)

        # log model params
        mlflow.log_params(model.get_params())

        # get prediction
        y_pred_train = model.predict(X_train_trans)
        y_pred_test  = model.predict(X_test_trans)

        # get the actual prediction values
        y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
        y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))

        # Calculate error
        test_error = mean_absolute_error(y_test,y_pred_test_org)
        train_error = mean_absolute_error(y_train,y_pred_train_org)

        mlflow.log_metric('train_mae',train_error)
        mlflow.log_metric('test_mae',test_error)

    return test_error

In [22]:
study = optuna.create_study(direction='minimize',study_name = 'model_selection')

with mlflow.start_run(run_name='Best Model'):
    
    study.optimize(objective,n_trials=30)

    mlflow.log_params(study.best_params)

    mlflow.log_metric('best_score',study.best_value)

[I 2026-04-05 14:27:15,411] A new study created in memory with name: model_selection

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001949 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
🏃 View run amusing-skunk-439 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/ef8561dafb8843ceb0de44f38baf3759
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:20,420] Trial 0 finished with value: 3.072000508580551 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 160, 'learning_rate_lgbm': 0.03563467926965561, 'max_depth_lgbm': 18, 'num_leaves': 105, 'min_data_in_leaf': 15}. Best is trial 0 with value: 3.072000508580551.

🏃 View run unequaled-worm-719 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/87fd414f34ef43f296a92023b0f65cd7
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:24,812] Trial 1 finished with value: 3.1151108741760254 and parameters: {'model': 'XGB', 'n_estimator_xgb': 131, 'learning_rate_xgb': 0.2658735378063197, 'max_depth_xgb': 7}. Best is trial 0 with value: 3.072000508580551.

🏃 View run traveling-pig-998 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/eae733f6612146f483243e721dd50bea
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:27,997] Trial 2 finished with value: 5.845482349395752 and parameters: {'model': 'XGB', 'n_estimator_xgb': 23, 'learning_rate_xgb': 0.019742846380709708, 'max_depth_xgb': 5}. Best is trial 0 with value: 3.072000508580551.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

🏃 View run amusing-moose-918 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/e93e61d576ca40ee84895cff2e012b7d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:39,691] Trial 3 finished with value: 3.1435528636719137 and parameters: {'model': 'GB', 'n_estimator_gb': 39, 'learning_rate_gb': 0.11188579423480768, 'max_depth_gb': 13}. Best is trial 0 with value: 3.072000508580551.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

🏃 View run dazzling-quail-541 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/df5a0517540548f2844030fd8ebd7c64
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:45,142] Trial 4 finished with value: 3.5303555384110785 and parameters: {'model': 'RF', 'n_estimator_rf': 92, 'max_depth_rf': 8}. Best is trial 0 with value: 3.072000508580551.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001747 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
🏃 View run vaunted-loon-715 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/78d193b7eb614141b8afd339edcf2260
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:27:49,596] Trial 5 finished with value: 3.171757207732918 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 37, 'learning_rate_lgbm': 0.0933027634205293, 'max_depth_lgbm': 14, 'num_leaves': 55, 'min_data_in_leaf': 46}. Best is trial 0 with value: 3.072000508580551.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

🏃 View run victorious-mule-813 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/7921c6dd05904e6eb24bad4b9b6e5a83
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:28:54,314] Trial 6 finished with value: 3.387017096017557 and parameters: {'model': 'GB', 'n_estimator_gb': 145, 'learning_rate_gb': 0.0774368890314974, 'max_depth_gb': 17}. Best is trial 0 with value: 3.072000508580551.

🏃 View run fun-shark-575 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/fcfa93eb656c4a838bfefaad7ca9ca8c
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:28:59,314] Trial 7 finished with value: 3.0442845821380615 and parameters: {'model': 'XGB', 'n_estimator_xgb': 124, 'learning_rate_xgb': 0.03739359304102626, 'max_depth_xgb': 8}. Best is trial 7 with value: 3.0442845821380615.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001569 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
🏃 View run sassy-goose-107 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/b65d60af7cc84f96ac6852d6e0b6133d
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:29:02,717] Trial 8 finished with value: 3.1640819991636198 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 45, 'learning_rate_lgbm': 0.07873657391115764, 'max_depth_lgbm': 12, 'num_leaves': 41, 'min_data_in_leaf': 44}. Best is trial 7 with value: 3.0442845821380615.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

🏃 View run adorable-calf-596 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/166c2ef0681646e2baeb7154edcffc00
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:29:20,430] Trial 9 finished with value: 3.110977353819565 and parameters: {'model': 'GB', 'n_estimator_gb': 36, 'learning_rate_gb': 0.1523921719516464, 'max_depth_gb': 12}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run debonair-quail-59 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/575da5f0bbf14f20815ae6e5ade08f27
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:29:40,913] Trial 10 finished with value: 3.287951707839966 and parameters: {'model': 'XGB', 'n_estimator_xgb': 200, 'learning_rate_xgb': 0.016484890793239226, 'max_depth_xgb': 18}. Best is trial 7 with value: 3.0442845821380615.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001765 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
🏃 View run charming-deer-908 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/7a591bd699d3491bb468b1473345e7d0
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:29:44,376] Trial 11 finished with value: 3.1793381050190277 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 194, 'learning_rate_lgbm': 0.018394855315685896, 'max_depth_lgbm': 20, 'num_leaves': 138, 'min_data_in_leaf': 10}. Best is trial 7 with value: 3.0442845821380615.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

🏃 View run sincere-robin-814 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/7756df7e2200482a8535b84aa8753170
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:29:53,634] Trial 12 finished with value: 3.0773892867682764 and parameters: {'model': 'RF', 'n_estimator_rf': 200, 'max_depth_rf': 20}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run peaceful-penguin-186 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/6b9900cc35f14fd6b18657b9db5a609c
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:00,902] Trial 13 finished with value: 3.162119150161743 and parameters: {'model': 'XGB', 'n_estimator_xgb': 104, 'learning_rate_xgb': 0.14320909889838299, 'max_depth_xgb': 13}. Best is trial 7 with value: 3.0442845821380615.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001662 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
🏃 View run resilient-zebra-559 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/6869f2a27fd0497ebdf03b35059732d5
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:04,245] Trial 14 finished with value: 3.4883493165664783 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 165, 'learning_rate_lgbm': 0.03230875901241991, 'max_depth_lgbm': 4, 'num_leaves': 120, 'min_data_in_leaf': 15}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run luminous-hare-501 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/e6331e2d20d94f09a98abe47298bd205
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:08,816] Trial 15 finished with value: 3.7732975482940674 and parameters: {'model': 'XGB', 'n_estimator_xgb': 112, 'learning_rate_xgb': 0.11281603865833133, 'max_depth_xgb': 2}. Best is trial 7 with value: 3.0442845821380615.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001503 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
🏃 View run thundering-wren-757 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/a8049ee52e1143279c6efd25e3f2084f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:12,486] Trial 16 finished with value: 3.067236733585493 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 124, 'learning_rate_lgbm': 0.051140670698278205, 'max_depth_lgbm': 20, 'num_leaves': 94, 'min_data_in_leaf': 23}. Best is trial 7 with value: 3.0442845821380615.
c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

🏃 View run aged-gnu-325 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/2ce96a761e084bcbaa6b3afc9dca88ad
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:16,914] Trial 17 finished with value: 5.865180071316406 and parameters: {'model': 'RF', 'n_estimator_rf': 29, 'max_depth_rf': 2}. Best is trial 7 with value: 3.0442845821380615.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001615 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
🏃 View run zealous-gnu-41 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/571617ee1b304577b4a8a991779b977f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:23,202] Trial 18 finished with value: 3.1741378131673446 and parameters: {'model': 'LGBM', 'n_estimator_lgbm': 112, 'learning_rate_lgbm': 0.0681809472127962, 'max_depth_lgbm': 5, 'num_leaves': 71, 'min_data_in_leaf': 29}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run sassy-kite-251 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/0da77a0ad5154e5eb49d965b1ec513c0
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:29,034] Trial 19 finished with value: 3.2478489875793457 and parameters: {'model': 'XGB', 'n_estimator_xgb': 171, 'learning_rate_xgb': 0.25150748933914346, 'max_depth_xgb': 12}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run amusing-bird-896 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/de439a075fa3479fa59000299e04cd69
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:34,968] Trial 20 finished with value: 3.0576794147491455 and parameters: {'model': 'XGB', 'n_estimator_xgb': 43, 'learning_rate_xgb': 0.08264937677183973, 'max_depth_xgb': 8}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run mercurial-finch-198 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/7b1d67267cf541228c1b80e9f7221e63
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:41,212] Trial 21 finished with value: 3.1351985931396484 and parameters: {'model': 'XGB', 'n_estimator_xgb': 33, 'learning_rate_xgb': 0.08257001341172246, 'max_depth_xgb': 8}. Best is trial 7 with value: 3.0442845821380615.

🏃 View run valuable-lark-422 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/0df79947ada0446898eb3d9372b3a869
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:46,954] Trial 22 finished with value: 3.0175349712371826 and parameters: {'model': 'XGB', 'n_estimator_xgb': 68, 'learning_rate_xgb': 0.0724477304551672, 'max_depth_xgb': 10}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run chill-crane-411 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/25a3a8c6ef85456886288c1d9f5e982f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:52,979] Trial 23 finished with value: 3.043560028076172 and parameters: {'model': 'XGB', 'n_estimator_xgb': 70, 'learning_rate_xgb': 0.06853923486504501, 'max_depth_xgb': 9}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run classy-fowl-324 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/53b21006841e49fe9396cd886daedc95
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:30:58,922] Trial 24 finished with value: 3.040212869644165 and parameters: {'model': 'XGB', 'n_estimator_xgb': 83, 'learning_rate_xgb': 0.05538086251633104, 'max_depth_xgb': 11}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run industrious-steed-20 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/3c5f250a634c4d33835263a0b87801fb
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:31:04,963] Trial 25 finished with value: 3.152824640274048 and parameters: {'model': 'XGB', 'n_estimator_xgb': 76, 'learning_rate_xgb': 0.07351492564571203, 'max_depth_xgb': 14}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run popular-elk-910 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/db55bf0fbf7e427da1e4c98046c7de58
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:31:10,924] Trial 26 finished with value: 3.1395535469055176 and parameters: {'model': 'XGB', 'n_estimator_xgb': 71, 'learning_rate_xgb': 0.21239506848589754, 'max_depth_xgb': 11}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run useful-shark-272 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/f57e2226b8b54d11950246a978b85310
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:31:16,949] Trial 27 finished with value: 3.02610182762146 and parameters: {'model': 'XGB', 'n_estimator_xgb': 71, 'learning_rate_xgb': 0.057628785043459634, 'max_depth_xgb': 10}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run abrasive-dove-903 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/1307580b7b954b21891e6d317c307b1f
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:31:23,302] Trial 28 finished with value: 3.2138681411743164 and parameters: {'model': 'XGB', 'n_estimator_xgb': 55, 'learning_rate_xgb': 0.1346035983479103, 'max_depth_xgb': 15}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run merciful-stag-41 at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/b4d115929c9d442db6f14bc11522a3c6
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

[I 2026-04-05 14:31:28,926] Trial 29 finished with value: 3.0389769077301025 and parameters: {'model': 'XGB', 'n_estimator_xgb': 91, 'learning_rate_xgb': 0.050408525596693995, 'max_depth_xgb': 11}. Best is trial 22 with value: 3.0175349712371826.

🏃 View run Best Model at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3/runs/cc954d6638a14d0192944513bff3f993
🧪 View experiment at: https://dagshub.com/jay-kanakia/swiggy_delivery_time_prediction.mlflow/#/experiments/3

In [23]:
study.best_params

{'model': 'XGB',
 'n_estimator_xgb': 68,
 'learning_rate_xgb': 0.0724477304551672,
 'max_depth_xgb': 10}

In [25]:
study.best_value

3.0175349712371826

In [26]:
xgb_params = {'n_estimator_xgb': 68,
 'learning_rate_xgb': 0.0724477304551672,
 'max_depth_xgb': 10}

In [27]:
xgb = XGBRegressor(**xgb_params)
xgb.fit(X_train_trans,y_train_pt)

c:\Users\Jay Kanakia\Desktop\CampusX\Projects\swiggy_delivery_time_prediction\myenv\Lib\site-packages\xgboost\training.py:200: UserWarning: [14:38:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "learning_rate_xgb", "max_depth_xgb", "n_estimator_xgb" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, learning_rate_xgb=0.0724477304551672,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_depth_xgb=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimator_xgb=68, ...)

In [29]:
# get the predictions
y_pred_train = xgb.predict(X_train_trans)
y_pred_test = xgb.predict(X_test_trans)

In [30]:
# get the actual predictions values

y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))

In [31]:
from sklearn.metrics import mean_absolute_error, r2_score

print(f"The train error is {mean_absolute_error(y_train,y_pred_train_org):.2f} minutes")
print(f"The test error is {mean_absolute_error(y_test,y_pred_test_org):.2f} minutes")

The train error is 2.63 minutes
The test error is 3.08 minutes

In [32]:
print(f"The train r2 score is {r2_score(y_train,y_pred_train_org):.2f}")
print(f"The test r2 score is {r2_score(y_test,y_pred_test_org):.2f}")

The train r2 score is 0.88
The test r2 score is 0.83

In [34]:
# dataframe of results

study.trials_dataframe().sample(2)

,number,value,datetime_start,datetime_complete,duration,params_learning_rate_gb,params_learning_rate_lgbm,params_learning_rate_xgb,params_max_depth_gb,params_max_depth_lgbm,params_max_depth_rf,params_max_depth_xgb,params_min_data_in_leaf,params_model,params_n_estimator_gb,params_n_estimator_lgbm,params_n_estimator_rf,params_n_estimator_xgb,params_num_leaves,state
14,14,3.488349,2026-04-05 14:30:00.902823,2026-04-05 14:30:04.245724,0 days 00:00:03.342901,NaN,0.032309,NaN,NaN,4.0,NaN,NaN,15.0,LGBM,NaN,165.0,NaN,NaN,120.0,COMPLETE
28,28,3.213868,2026-04-05 14:31:16.949354,2026-04-05 14:31:23.302102,0 days 00:00:06.352748,NaN,NaN,0.134604,NaN,NaN,NaN,15.0,NaN,XGB,NaN,NaN,NaN,55.0,NaN,COMPLETE

In [36]:
study.trials_dataframe()['params_model'].value_counts()

params_model
XGB     17
LGBM     7
GB       3
RF       3
Name: count, dtype: int64

In [40]:
study.trials_dataframe().groupby(['params_model'])['value'].mean().sort_values()

params_model
LGBM    3.188129
GB      3.213849
XGB     3.314212
RF      4.157642
Name: value, dtype: float64

In [42]:
score  = cross_val_score(xgb,X_train_trans,y_train_pt,scoring='neg_mean_absolute_error',cv=5,n_jobs=-1)
score

array([-0.35230818, -0.34758249, -0.34491307, -0.34600523, -0.34557638])

In [44]:
model = TransformedTargetRegressor(regressor=xgb,transformer=pt)

In [47]:
score  = cross_val_score(model,X_train_trans,y_train,scoring='neg_mean_absolute_error',cv=5,n_jobs=-1)
score

array([-3.20069432, -3.13977528, -3.13746285, -3.12068963, -3.12642002])

### Visualization

In [48]:
optuna.visualization.plot_optimization_history(study)

In [49]:
# parallel coordinate plot

optuna.visualization.plot_parallel_coordinate(study,params=["model"])